config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :messages, only: [:create]
resources :rooms, only: [:create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
 # get 'search', to: 'application#search', as:search
  get "search" => "searches#search"
  #get 'search', to: 'users#search', as:search
  
  get "home/about"=>"homes#about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
 end
   resources :users, only: [:index,:show,:edit,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
   get :followings, :followers
  end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  
  validates :name,  length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user= User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
    
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
  followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :set_user, only: [:followings, :followers]


  def show
    @user = User.find(params[:id])
     @book = Book.new
    @books = @user.books
  end


  def index
    @users = User.all
    @book = Book.new
  end

  def edit
     user_id = params[:id].to_i
  unless user_id == current_user.id
    redirect_to user_path(current_user)
  end
    @user = current_user
  end

  def update
       @user = current_user
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

   def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
   end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end


  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
   <tr>
  <th>follows</th>
  <th>
    <%= link_to followings_user_path(user) do %>
    <%= user.followings.count %>
    <%end%>
    </th>
   </tr>
   <tr>
  <th>follower</th>
  <th>
    <%= link_to "#{user.followers.count}" ,followers_user_path(user) %>
 </th>
   </tr>
</table>


<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_info1.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
   <tr>
  <th>follows</th>
  <th>
    <%= link_to followings_user_path(user) do %>
    <%= user.followings.count %><%end%>
    </th>
   </tr>
   <tr>
  <th>follower</th>
  <th><%= link_to "#{user.followers.count}" ,followers_user_path(user) %></th>
   </tr>
</table>

<p class="btn btn-success">
<% if current_user.following?(user) %>
  <%# p class="text-light" %>
  <%= link_to "フォロー外す", user_relationships_path(user.id) ,method: :delete , class: "text-light" %>
  </p> <%= link_to "chatを始める", chat_path(@user.id) %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post ,class: "text-light" %>

<% end %>
</p>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>followerUsers</h1>

  <% @users.each do |user| %>
  <%= user.name %>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
<div class="row">
  <div class="col-md-3">
<h2>User info</h2>
<%= render 'info', user: current_user%>
<h2 class="mt-3">New book</h2>
<%= render "books/form", book: @book ,action: "new" %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<%= render 'index',users: @users %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info1', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book ,action: "new" %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
     <%= render 'books/index',books: @books ,book: @book %>
  </div>
  </div>
</div>