config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :messages, only: [:create]
resources :rooms, only: [:create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
 # get 'search', to: 'application#search', as:search
  get "search" => "searches#search"
  #get 'search', to: 'users#search', as:search
  
  get "home/about"=>"homes#about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
 end
   resources :users, only: [:index,:show,:edit,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
   get :followings, :followers
  end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy
  validates :title,presence: true
  validates :body,presence: true,length:{maximum:200}
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
   def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
   end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new=Book.new
    @user = @book.user
    @book_comment  = BookComment.new
    
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
  end

  def index
     @user = current_user
     to = Time.current.at_end_of_day
     from = (to - 6.day).at_beginning_of_day
     @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
     @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
        flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user=current_user
      render 'index'
    end
  end

  def edit
    book_id = Book.find(params[:id])
  unless book_id.user == current_user
    redirect_to books_path
  end

    @book = Book.find(params[:id])
  end

  def update
    book_id = Book.find(params[:id])
  unless book_id.user == current_user
    redirect_to books_path
  end

    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body , :user_id)
  end
 end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
   <table>
             <% book.book_comments.each do |book_comment| %>
              <tr>
                <td>
             <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
             <%= book_comment.user.name %>
             </td>
             <td>
             <%= book_comment.comment %>
              </td>
              <% if book_comment.user == current_user %>
              <td>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete , remote: true ,class: "btn btn-sm btn-danger" %>
               </td>
                 <% end %>
             </tr>
             <% end %>
      </table>  

app/views/books/_commentcount.html.erb
<%= book.book_comments.count %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
         <%= link_to book_favorites_path(book), method: :delete , remote: true do %>
        ♥<%= book.favorites.count %> いいね
<%end%>
        <% else %>
        <%= link_to book_favorites_path(book), method: :post , remote: true do %>
        ♡<%= book.favorites.count %> いいね
<%end%>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <% if action == "new" %>
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
    <% else %>
    <%= f.submit 'Update Book', class: 'btn btn-success' %>
    <% end %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image , size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td> 
    </tr>
    <% end %>
    
     
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render "layouts/errors", obj: @book %>
  		<%= render 'form', book: @book, action: "edit" %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
 <%= render "layouts/errors", obj: @book %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book ,action: "new"%>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
    
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image , size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id='favorite_buttons_<%= book.id %>'>
        <%= render 'books/favorite' ,book: book %>
        </td>
        <td>
        コメント件数：<%= @book.book_comments.count %>
        
        </td>
    </tr>
    <% end %>
    
     
  </tbody>
</table>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' , user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new ,action: "new" %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
         <td id='favorite_buttons_<%= @book.id %>'>
         <%= render 'books/favorite' ,book: @book %>
        </td>
            <td id="commentsCount">
            コメント件数：
            <%= render 'books/commentcount' ,book: @book %>
             </td>
              <td class="view-count">
              閲覧数: <%= @book.view_counts.count %></td>
                
           <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
             <% end %></td>

        </tr>
      </table>
            <div id="comments_area"> 
            <%= render 'books/comment' ,book: @book %>
            </div>
            
            <%= form_with model: [@book, @book_comment] , local: false do |f| %>
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
            <br>
            <%= f.submit "送信する" %>
            <% end %>
    </div>
  </div>
</div>